let arr = [1, 2, 3, 4, 5];

console.log(arr); // THIS WILL PRINT THE ENTIRE ARRAY.

// IN C++ WE HAD VECTOR FOR DYNAMIC ARRAYS, IN JAVASCRIPT WE HAVE ARRAYS WHICH ARE DYNAMIC BY DEFAULT. i.e. WE CAN ADD OR REMOVE ELEMENTS FROM THE ARRAY WITHOUT ANY ISSUE. UNLIKE C++.

arr.push(6); // THIS WILL ADD 6 TO THE END OF THE ARRAY.
console.log("PUSH " + arr); 

arr.pop(); // THIS WILL REMOVE THE LAST ELEMENT FROM THE ARRAY.
console.log("POP " + arr);

arr.unshift(0); // THIS WILL ADD 0 TO THE BEGINNING OF THE ARRAY.
console.log("UNSHIFT " + arr);

arr.shift(); // THIS WILL REMOVE THE FIRST ELEMENT FROM THE ARRAY.
console.log("SHIFT " + arr);

// WE CAN ACCEESS ELEMENTS OF THE ARRAY USING INDEXES, JUST LIKE IN C++.

console.log("iNDEX 0 :" + arr[0]); // THIS WILL PRINT THE FIRST ELEMENT OF THE ARRAY.

// WE CAN ALSO USE FOR LOOPS TO ITERATE THROUGH THE ARRAY.

console.log("ITERATING THROUGH THE ARRAY USING A FOR LOOP : ");

let size = arr.length; // THIS WILL GIVE THE SIZE OF THE ARRAY.

for(let i = 0; i<size; i++) {
    console.log(arr[i]); // THIS WILL PRINT EACH ELEMENT OF THE ARRAY.
}


// MAKING A CONST ARRAY... : 

console.log("CONST ARRAY EXAMPLE : ");

const arr2 = [10, 20, 30, 40, 50];
console.log("CONST ARRAY : " + arr2);
arr2.push(60); 
arr2[0] = 5; 
console.log("MODIFIED CONST ARRAY : " + arr2); 

// UNLIKE CONST VARIABLES, CONST ARRAYS CAN BE MODIFIED. WE CAN ADD OR REMOVE ELEMENTS FROM A CONST ARRAY, BUT WE CANNOT REASSIGN THE ENTIRE ARRAY TO A NEW VALUE.

// arr2 = [1, 2, 3]; // THIS WILL THROW AN ERROR BECAUSE WE CANNOT REASSIGN A CONST ARRAY.
// arr2 = "NEW ARRAY"; // THIS WILL ALSO THROW AN ERROR BECAUSE WE CANNOT REASSIGN A CONST ARRAY.

// IN JAVASCRIPT, ARRAY CAN HOLD ELEMENTS OF DIFFERENT DATA TYPES, UNLIKE C++ WHERE AN ARRAY CAN ONLY HOLD ELEMENTS OF THE SAME DATA TYPE.

console.log("ARRAY WITH DIFFERENT DATA TYPES : ");

let arr3 = [1, "Hello", true, 3.14, 'A', [1, 2, 3],]; 
console.log(arr3); 


// MAKING A 2D ARRAY IN JAVASCRIPT :

console.log("2D ARRAY EXAMPLE : ");
let arr4 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]];
console.log(arr4); // THIS WILL PRINT THE 2D ARRAY.

// EACH ARRAY INSIDE THE MAIN ARRAY IS CALLED A ROW, AND EACH ELEMENT INSIDE THE ROW IS CALLED A COLUMN. WE CAN ACCESS ELEMENTS OF THE 2D ARRAY USING TWO INDEXES, FIRST FOR THE ROW AND SECOND FOR THE COLUMN.

console.log("ACCESSING ELEMENTS OF THE 2D ARRAY : ");

console.log("First element : " + arr4[0][0]); // THIS WILL PRINT THE FIRST ELEMENT OF THE FIRST ROW, WHICH IS 1.

console.log("Middle element : " + arr4[1][1]); // THIS WILL PRINT THE MIDDLE ELEMENT OF THE SECOND ROW, WHICH IS 5.

// UNLIKE C++, IN JAVASCRIPT WE CAN HAVE JAGGED ARRAYS, WHICH ARE ARRAYS OF ARRAYS WITH DIFFERENT LENGTHS.

console.log("JAGGED ARRAY EXAMPLE : ");
let arr5 = [[1, 2], [3, 4, 5], [6]];
console.log(arr5); // THIS WILL PRINT THE JAGGED ARRAY.

// 2D ARRAYS CAN ALSO CONTAIN ELEMENTS OF DIFFERENT DATA TYPES, JUST LIKE 1D ARRAYS.

console.log("2D ARRAY WITH DIFFERENT DATA TYPES : ");
let arr6 = [[1, "Hello"], [true, 3.14], ['A', [1, 2, 3]]];
console.log(arr6); // THIS WILL PRINT THE 2D ARRAY WITH DIFFERENT DATA TYPES.