console.log("Hello, World!"); // console.LOG IS SIMILAR TO PRINT IN OTHER LANGUAGES, IT DISPLAYS THE OUTPUT IN THE CONSOLE.   

console.log("3 + 4"); // IF USED WITH (" "), IT'S A STRING, NOT A MATH OPERATION. IT WILL JUST DISPLAY "3 + 4" IN THE CONSOLE.

console.log(3 + 4); // WITHOUT THE QUOTES, IT WILL PERFORM THE MATH OPERATION AND DISPLAY THE RESULT, WHICH IS 7.

console.log("The result of 3 + 4 is: " + (3 + 4)); // THIS WILL CONCATENATE THE STRING WITH THE RESULT OF THE MATH OPERATION.  

let result = 3 + 4; // NO NEED OF DATATYPE IN JAVASCRIPT, IT AUTOMATICALLY DETERMINES THE TYPE BASED ON THE VALUE ASSIGNED.
// KEYWORDS LIKE LET, CONST, AND VAR ARE USED TO DECLARE VARIABLES IN JAVASCRIPT.

console.log("The result is: " + result);
// VARIABLES CAN BE USED TO STORE VALUES AND REUSE THEM LATER IN THE CODE. IN THIS CASE, WE STORED THE RESULT OF 3 + 4 IN A VARIABLE CALLED "result" AND THEN DISPLAYED IT IN THE CONSOLE.

a = 2;
b = 3;
c = a * b;
console.log(a,b,c);
// THIS WAY USING COMMAS, WE CAN PRINT MULTIPLE VARIABLES IN A SINGLE CONSOLE.LOG STATEMENT. IT WILL DISPLAY THE VALUES OF a, b, AND c SEPARATED BY SPACES. 

// SAME THING CAN BE DONE FOR STRINGS AS WELL...SEPARATE DIFFERENT STRINGS WITH COMMAS IN A SINGLE CONSOLE.LOG STATEMENT.

console.log("The value of a is:", a, "and the value of b is:", b, "so the result of a * b is:", c);
// THIS WILL DISPLAY THE STRING AND THE VALUES OF a, b, AND c IN A SINGLE LINE IN THE CONSOLE.

// PLUS (+) OPERATOR CAN ALSO BE USED TO CONCATENATE STRINGS AND VARIABLES, BUT IT MAY NOT ADD SPACES AUTOMATICALLY.

