// IF-ELSE STATEMENTS HERE ARE SIMILAR TO OTHER LANGUAGES.
// AND THE SYNTAX IS ALSO SIMILAR TO C++. NOTHING NEW!! 
// ALSO THE ELSE-IF LADDER IS ALSO SIMILAR TO C++.
// MULTIPLE CODITONS CAN ALSO BE CHECKED USING LOGICAL OPERATORS (&&, ||, !), JUST LIKE IN C++.


// WHAT'S NEW HERE IS...AS YOU CAN SEE BELOW : 

let a = 5;
let b = 5;
console.log(a == b); // IT SYAS TRUE.

// NOW, IF WE MAKE A LITTLE CHANGE IN THE CODE, LIKE THIS :

let c = 5;
let d = "5";
console.log(c == d); // IT ALSO SAYS TRUE. HOW??? AS IN C++, IF WE COMPARE INT WITH STRING, IT WILL CONVERT THE STRIN TO ASCII VALUE OF CHARACTER "5" AND THEN COMPARE. 
// BUT IN JAVASCRIPT, IT CONVERTS THE STRING "5" TO NUMBER 5 AND THEN COMPARES. THIS IS CALLED TYPE COERCION IN JAVASCRIPT.

// HERE, == COMPARES VALUE ONMLY, NOT THE DATA TYPE. THIS IS CALLED LOOSE EQUALITY IN JAVASCRIPT.

// TO AVOID THIS, WE DO THE BELOW : 

console.log(c === d); // THIS SAYS FALSE. AS === COMPARES BOTH VALUE AND DATA TYPE. THIS IS CALLED STRICT EQUALITY IN JAVASCRIPT.

// SIMILARLY, FOR NOT EQUAL TO, WE HAVE != AND !== OPERATORS IN JAVASCRIPT. 
// != CHECKS ONLY VALUE, WHILE !== CHECKS BOTH VALUE AND DATA TYPE.






