// WE CAN USE BACKTICKS (``) (just above TAB) FOR STRINGS INSTEAD OF QUOTES.
// THIS GIVES STRINGS SOME SUPERPOWERS...

// 1. INJECTION OF VARIABLES: WE HAD TWO METHODS...EITHER USE '+' OR COMMAS (,). BUT INSTEAD OF USING BUNCH OF PLUS SIGNS OR COMMAS, WE CAN DROP THE VARIABLE DIRECTLY INTO THE STRING USING ${VBL.} IF WE PUT THE STRING IN BAKCTICKS INSTEAD OF QUOTES.

let age = 18;
let name = "Noman";

console.log(`My name is ${name} and I am ${age} years old.`)

// ANOTHER BENEFIT IS : USING BACKTICKS WE CAN WRITE OUR STRING IN MULTIPLE LINES, WITHOUT BREAKING OUR CODE. AND JS WILL PRINT IT EXACTLY AS WE WROTE IT. WHICH IS NOT POSSIBLE IN CASE OF QUOTES.

let message = `This is line one.
This is line two.
Look, no errors!`;
console.log(message);

// AND WE CAN ALSO DO MATHEMATICAL CALCULATION INSIDE OF A STRING...

let price = 100;
let tax = 5;

console.log(`Total price is: ${price + tax}`);
